//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonsWhoIsEmployees", ReplyAction="http://tempuri.org/IService1/GetPersonsWhoIsEmployeesResponse")]
        System.Data.DataTable GetPersonsWhoIsEmployees(string letter, bool isFirstLetter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPersonsWhoIsEmployees", ReplyAction="http://tempuri.org/IService1/GetPersonsWhoIsEmployeesResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetPersonsWhoIsEmployeesAsync(string letter, bool isFirstLetter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApp.ServiceReference2.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApp.ServiceReference2.IService1>, WebApp.ServiceReference2.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetPersonsWhoIsEmployees(string letter, bool isFirstLetter) {
            return base.Channel.GetPersonsWhoIsEmployees(letter, isFirstLetter);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetPersonsWhoIsEmployeesAsync(string letter, bool isFirstLetter) {
            return base.Channel.GetPersonsWhoIsEmployeesAsync(letter, isFirstLetter);
        }
    }
}
